config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin_home', as: 'rails_admin'
  devise_for :users, path: 'users', controllers: { sessions: "users/sessions", registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks'}
  devise_for :admins, path: 'admins', controllers: { sessions: "admins/sessions", registrations: 'admins/registrations'}
  root 'home#index'
  resources :profile, :only => [:index, :show]
  resources :home, :only => [:index]
  resources :leaderboard, :only => [:index]
  resources :myquizzes, :only => [:index]
  resources :genres, :only => [:show] do
    resources :subgenres, :only => [] do
      resources :questions, :only => []
      resources :quizzes, :only => [:create, :edit, :destroy, :update]
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :name, presence: true, length: { minimum: 1, maximum: 40 }
  validates :description, presence: true, length: { minimum: 1, maximum: 400 }
  has_many :subgenres, dependent: :destroy
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :authenticate_admin!, except: [:show]
  before_action :authenticate_any!, only: [:show]
  before_action :set_genre, only: [:show, :edit, :update, :destroy]
  def index
    @genres = Genre.all
  end
  def new
    @genre = Genre.new
  end
  def create
    @genre = Genre.create(genre_params)
    if @genre.save
      flash[:success] = "New genre has been created!"
      redirect_to genres_path
    else
      flash[:alert] = "New genre couldn't be created!  Please check the form."
      render :new
    end
  end
  def show
  end
  def edit
  end
  def update
    if @genre.update(genre_params)
      flash[:success] = "genre updated."
      redirect_to genres_path
    else
      flash.now[:alert] = "Update failed. Please check the form."
      render :edit
    end
  end
  def destroy
    @genre.destroy
    redirect_to genres_path
  end
  private

  def genre_params
    params.require(:genre).permit(:name, :description)
  end
  def set_genre
    @genre = Genre.find(params[:id])
  end

  def authenticate_any!
    if admin_signed_in?
        true
    else
        authenticate_user!
    end
  end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/_form.html.haml
.form-wrapper
  = form_for @genre do |f|
    .field
      = f.label :name
      %br/
      = f.text_field :name, autofocus: true
    .field
      = f.label :description
      %br/
      = f.text_field :description
    .actions
      = f.submit "Submit"

app/views/genres/edit.html.haml
= render 'form'
.text-center.edit-links
  = link_to "Delete genre", genre_path(@genre), method: :delete, data: { confirm: "Are you sure you want to delete this genre?" }
  |
  = link_to "cancel", genres_path

app/views/genres/index.html.haml
-@genres.each do |genre|
  .row
    = link_to (genre.name), genre_path(genre)
    %p= genre.description
    - if genre.subgenres
      - genre.subgenres.each do |subgenre|
        .subgenre
          .subgenre-name
            = subgenre.name
          .subgenre-content
            = subgenre.description
    .comment-form.col-sm-11
      = form_for [genre, genre.subgenres.new] do |f|
        = f.text_field :name, placeholder: 'Add subgenre name...'
        = f.text_field :description, placeholder: 'Add subgenre description...'
        = f.submit "Submit"

app/views/genres/new.html.haml
%h2 New Genre
= render 'form'

app/views/genres/show.html.haml
.content-holder
  = react_component("GenrePage", props: { userDetails: current_user.to_json(only: ["quizzes"], include: ["quizzes" => { only: ["id", "hasFinished", "subgenre"], include: ["subgenre" => {only: ["id"]}]}]), Genre: @genre.to_json(only: ["id", "name", "description", "subgenres"], include: ["subgenres" => {only: ["name", "description", "id"]}]), authenticity_token: form_authenticity_token}, prerender: true)