config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin_home', as: 'rails_admin'
  devise_for :users, path: 'users', controllers: { sessions: "users/sessions", registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks'}
  devise_for :admins, path: 'admins', controllers: { sessions: "admins/sessions", registrations: 'admins/registrations'}
  root 'home#index'
  resources :profile, :only => [:index, :show]
  resources :home, :only => [:index]
  resources :leaderboard, :only => [:index]
  resources :myquizzes, :only => [:index]
  resources :genres, :only => [:show] do
    resources :subgenres, :only => [] do
      resources :questions, :only => []
      resources :quizzes, :only => [:create, :edit, :destroy, :update]
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/subgenre.rb
class Subgenre < ApplicationRecord
  validates :name, presence: true, length: { minimum: 1, maximum: 40 }
  validates :description, presence: true, length: { minimum: 1, maximum: 400 }
  belongs_to :genre
  has_many :questions, dependent: :destroy
  has_many :quizzes, dependent: :destroy
end

app/controllers/subgenres_controller.rb
class SubgenresController < ApplicationController
  before_action :authenticate_admin!, except: [:show]
  before_action :authenticate_any!, only: [:show]
  before_action :set_genre

  def show
  	@subgenre = @genre.subgenres.find(params[:id])
  end
  def create
    @subgenre = @genre.subgenres.build(subgenre_params)

    if @subgenre.save
      flash[:success] = "You made a new subgenre for that genre!"
      redirect_back fallback_location: root_path
    else
      flash[:alert] = "Check the subgenre form, something went wrong."
      render root_path
    end
  end

  def destroy
    @subgenre = @genre.subgenres.find(params[:id])

    @subgenre.destroy
    flash[:success] = "Subgenre deleted."
    redirect_to root_path
  end

  private

  def subgenre_params
    params.require(:subgenre).permit(:name, :description)
  end

  def set_genre
    @genre = Genre.find(params[:genre_id])
  end

  def authenticate_any!
    if admin_signed_in?
        true
    else
        authenticate_user!
    end
  end
end

app/helpers/subgenres_helper.rb
module SubgenresHelper
end

app/views/subgenres/show.html.haml
.row
  %p= @subgenre.name
  %p= @subgenre.description
- if @subgenre.questions
  - @subgenre.questions.each do |question|
    .question
      .question-name
        = question.question
        - if question.image?
          = image_tag question.image.url(:medium)
        - if question.audio?
          = audio_tag question.audio.url
      .question-name
        = question.option1
      .question-name
        = question.option2
      .question-name
        = question.option3
      .question-name
        = question.option4
      .question-content
        = question.answer
        = link_to genre_subgenre_question_path(@genre, @subgenre, question), method: :delete, data: { confirm: "Are you sure?" }, remote: true do
          %span(class="glyphicon glyphicon-remove delete-question")
.form.col-sm-12
  = form_for [@genre, @subgenre, @subgenre.questions.new], remote: true do |f|
    = f.text_field :question, placeholder: 'Add question...'
    = f.text_field :option1, placeholder: 'Add option1...'
    = f.text_field :option2, placeholder: 'Add option2...'
    = f.text_field :option3, placeholder: 'Add option3...'
    = f.text_field :option4, placeholder: 'Add option4...'
    = f.text_field :answer, placeholder: 'Add Answer...'
    = f.file_field :image
    = f.file_field :audio
    = f.submit "Submit"
.text-center.edit-links
  = link_to "Cancel", genre_subgenres_path
  |
  = link_to "Edit subgenre", edit_genre_subgenre_path(@subgenre)