config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin_home', as: 'rails_admin'
  devise_for :users, path: 'users', controllers: { sessions: "users/sessions", registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks'}
  devise_for :admins, path: 'admins', controllers: { sessions: "admins/sessions", registrations: 'admins/registrations'}
  root 'home#index'
  resources :profile, :only => [:index, :show]
  resources :home, :only => [:index]
  resources :leaderboard, :only => [:index]
  resources :myquizzes, :only => [:index]
  resources :genres, :only => [:show] do
    resources :subgenres, :only => [] do
      resources :questions, :only => []
      resources :quizzes, :only => [:create, :edit, :destroy, :update]
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-default
  .container-fluid.navbar-container
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#bs-navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle Navigation
        %span.icon-bar
        %span.icon-bar
      .navbar-left
        =link_to (image_tag "Icon.png", :style => "height: 60px; padding-right:10px"), root_path
        =link_to "QuizApp", root_path
    .collapse.navbar-collapse#bs-navbar-collapse-1
      %ul.nav.navbar-nav.navbar-right
        - if admin_signed_in?
          %li
            = link_to "ADMIN Home", rails_admin_path
          %li
            = link_to "ADMIN Logout", destroy_admin_session_path, method: :delete
        - if user_signed_in?
          %li
            = link_to "Home", root_path
          %li
            = link_to "My Profile", profile_index_path
          %li
            = link_to "LeaderBoard", leaderboard_index_path
          %li
            = link_to "My Quizzes", myquizzes_path
          %li
            = link_to "Logout", destroy_user_session_path, method: :delete
        - else
          %li
            = link_to "Login", new_user_session_path
          %li
            = link_to "Register", new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title QuizApp
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'hello-world-bundle'
  %body
    = render 'layouts/navbar'
    .container
      -flash.each do |name, msg|
        = content_tag :div, msg, class: [:alert, alert_for(name)]
      = yield

app/views/layouts/hello_world.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReactOnRailsWithWebpacker</title>
    <%= csrf_meta_tags %>
    <%= javascript_pack_tag 'hello-world-bundle' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>